
version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - activity-tracking
      - analytics
      - authservice
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: e2e.Dockerfile
    networks:
      - app_network

  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_DB=activitydb
      - MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app_network

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_DB=activitydb
      - MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
      - PYTHONUNBUFFERED=1 # to make print statements visible
    depends_on:
      - mongodb
    networks:
      - app_network

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_DATABASE=authdb
      - SPRING_DATA_MONGODB_URI=mongodb://root:cfgmla23@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cfgmla23
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app_network

  cypress:
    build:
      context: ./cypress-test
      dockerfile: Dockerfile
    working_dir: /cypress-test 
    environment:
      - CYPRESS_API_GATEWAY_URL=http://172.20.0.1
      - CYPRESS_MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
    depends_on:
      - nginx
      - mongodb
    volumes:
      - ./cypress-test:/cypress-test/
    command: npx cypress run 
    networks:
      - app_network

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - app_network

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=cfgmla23
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - app_network

networks:
  app_network:
    name: mla_app_network
    driver: bridge

volumes:
  mongodb-data:
  grafana_data:
