# docker-compose -f docker-compose-cypress.yaml up 
# docker compose --env-file ./.env.test.local -f docker-compose-cypress.yaml up --build
version: "3.8"
services:
    
  cypress:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /cypress-test 
    environment:
      - CYPRESS_API_GATEWAY_URL=http://172.19.0.1
      - CYPRESS_MONGO_URI=mongodb://root:cfgmla23@172.19.0.3:27017
    volumes:
      - ./:/cypress-test/
    command: npx cypress run 
    # command: ping 127.0.0.1
    # command: ping frontend
    networks:
      - proxy_net

networks:
  proxy_net:
    external: 
      name: mla_app_network