name: Nginx ECR Deployment

on:
  push:
    branches:
      - main
      - ma_task5
    paths:
      - "nginx/**"

jobs:
  build:
    name: Deploy Nginx to ECR
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Nginx Docker Image
        run: |
          cd nginx
          docker build -t mla-fitness-nginx:latest .
          docker tag mla-fitness-nginx:latest ${{ steps.login-ecr.outputs.registry }}/mla-fitness-nginx:latest

      - name: Push Nginx Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/mla-fitness-nginx:latest
