name: MongoDB ECR Deployment

on:
  push:
    branches:
      - main
      - ma_task5
    paths:
      - "mongodb/**"

jobs:
  build:
    name: Deploy MongoDB to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag MongoDB Docker Image
        run: |
          cd mongodb
          docker build -t mla-fitness-mongodb:latest \
            --build-arg MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
            --build-arg MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} .

      - name: Tag MongoDB Docker Image
        run: |
          docker tag mla-fitness-mongodb:latest ${{ steps.login-ecr.outputs.registry }}/mla-fitness-mongodb:latest

      - name: Push MongoDB Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/mla-fitness-mongodb:latest
